### ISSUE TITLE
Missing 0.5.5 git tag

### ISSUE THREAD

**Issue by yan12125** [getmoto/py-partiql-parser#22]
There is https://pypi.org/project/py-partiql-parser/0.5.5/ but no 0.5.5 in  https://github.com/getmoto/py-partiql-parser/tags. Maybe the reason is the failed step at https://github.com/getmoto/py-partiql-parser/actions/runs/9045536986/job/24855400118 ?

**Comment by bblommers** [comment]
Correct @yan12125 - the permissions stopped working since the last release.

This has been [fixed](https://github.com/getmoto/py-partiql-parser/commit/6c9ebe216ce8c22db185d0a14d7aa94e1dc6b2f0) already, so I expect next time to have a proper Github release again.

**Comment by yan12125** [comment]
A new tag https://github.com/getmoto/py-partiql-parser/releases/tag/0.5.6 is out, thanks!
