### ISSUE TITLE
Version tagged as 0.3.4 is still 0.3.3

### ISSUE THREAD

**Issue by s-t-e-v-e-n-k** [getmoto/py-partiql-parser#4]
Subject says everything -- the code in main still shows 0.3.3 in pyproject.toml, but there's a tag of 0.3.4.

**Comment by bblommers** [comment]
Thanks @s-t-e-v-e-n-k - I'll update this shortly and release a new version

**Comment by bblommers** [comment]
Done! https://pypi.org/project/py-partiql-parser/0.3.5/
