### ISSUE TITLE
/tests/ shouldn't be explicitly listed in dependencies

### ISSUE THREAD

**Issue by fstrzalka** [getmoto/py-partiql-parser#8]
https://github.com/getmoto/py-partiql-parser/commit/b2e88929ff68878229f0c6981fea7ef721456d8f

This is an antipattern and actually causes errors when importing packages that are using Your package by downloading from github - as (on the other hand) a very common pattern is to use \tests\ as an internal module in many python projects.
Are You sure this is even necessary?

**Comment by bblommers** [comment]
Hi @fstrzalka, it sounds like you and #9 have the same problem. In short: No, this is not necessary - we'll switch to using `MANIFEST.in` in the next release.

**Comment by bblommers** [comment]
OK, this should be fixed with 0.3.7. The `wheel` only has the source files, the `sdist` has both source and test.

Thanks for raising this @fstrzalka  - just let us know if you run into any other issues.
