### ISSUE TITLE
`tests` gets installed as a Python module in `site-packages`

### ISSUE THREAD

**Issue by Lef-F** [getmoto/py-partiql-parser#9]
Hi, I recently stumbled upon an issue when executing `pylint` against my `tests`.

Running `pylint tests` looks for `tests` Python modules in my local environment and then in the local path, which ends up testing your `tests` module instead of my local `tests` folder.

The workaround is to pass in an explicit path i.e. `pylint $(pwd)/tests`.

The question is: is it necessary for you that the `tests` module from `py-partiql-parser` gets installed in the user's virtual environment?

https://github.com/getmoto/py-partiql-parser/blob/1d9376e281fc46e170f4e34b62445e94c1686d6e/pyproject.toml#L17-L22

**Comment by bblommers** [comment]
Hey @Lef-F! No, that's not necessary at all. I just wanted to ensure that the `tests`-directory is included in the package, but I didn't think that the current approach would create separate modules. 

We should probably just use `MANIFEST.in` to specify the additional directories.
